export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const AUTHENTICATING = 'AUTHENTICATING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SERVER_AUTH_ERROR = 'SERVER_AUTH_ERROR';
